### PR TITLE
Include HTML entities to the applications list

### PR DESCRIPTION
**Pull request by sinourain**
This should enable the app to run correctly in production.

### CODE REVIEW

**Comment by martinsvalin** [comment]
Is this not inferred from the dependencies since Elixir 1.4?

**Comment by sinourain** [comment]
I think that for some persons it should be useful.

**Comment by josevalim** [comment]
This is definitely not necessary, it will always be inferred in the case extra_applications is used. :)

**Comment by martinsvalin** [comment]
Thanks for the input!

**Pull request closed without merging**
