### PR TITLE
Replace deprecataed String.rstrip with String.trim_trailing

### PR DESCRIPTION
**Pull request by nallwhy**

### CODE REVIEW

**Comment by jwarlander** [comment]
The change itself looks good, but could need a unit test; eg. something like the following, in `test/html_entities/util_test.ex`:

```elixir
  test "Trailing whitespace is removed from entity descriptions" do
    assert convert_lines_to_entities(["euro,€,8364 \t"]) == [{"euro","€","8364"}]
  end
```

However, a more controversial detail is that the change would imply you need Elixir 1.3+ (instead of the 1.0 requirement that's currently in `mix.exs`). Strictly speaking, of course, we're still in pre-1.0 mode, but the package *has* seen [a fair amount of downloads via hex.pm](https://hex.pm/packages/html_entities), and is used as a dependency in [a few other packages](https://hex.pm/packages?search=depends%3Ahtml_entities).

What do you think, @martinsvalin?

**Comment by jinkyou** [comment]
As this module is stable, I think it's good to set required Elixir version to 1.3+ and bump to v0.4.
Then users who use Elixir < 1.3 can keep using v0.3.

**Comment by nallwhy** [comment]
As this module is stable, I think it's good to set required Elixir version to 1.3+ and bump to v0.4.
Then users who use Elixir < 1.3 can keep using v0.3.

**Comment by martinsvalin** [comment]
Thank you @nallwhy!
I think it's entirely fair to update `mix.exs` to require Elixir 1.3+. It's important to be able to use a library without getting warnings. Can you update the PR?

**Comment by nallwhy** [comment]
@jwarlander Thank you for a good test code.
@martinsvalin Updated. Thanks :)

**Comment by jwarlander** [comment]
Thanks, @nallwhy!

**Comment by martinsvalin** [comment]
Thank you both. I've released 0.4.0 on hex.pm after some housekeeping.

**Pull request merged**
